cookie:
  expiry_days: 30
  key: CHANGE_ME_use_streamlit_secrets_toml
  name: nsia_auth

credentials:
  usernames:
    admin:
      email: admin@nsia.org
      name: NSIA Admin
      password: $2b$12$QjyjLnEseMSldoAzi10Bfej2eqdw28s15bFRX5TqOibJ1CZG0YTAq
      role: admin
    board:
      email: board@nsia.org
      name: Board Member
      password: $2b$12$6Tgi/RbZMLePN8gOGOpdSuP25bTZlPA43n0SaRWHlF9MbGDDV/sGy
      role: board
    winnetka:
      email: winnetka@nsia.org
      name: Winnetka Rep
      password: $2b$12$L6/o.HwzUwURTFrLajOapOjCgxeH90UemKcR58OYZVL.o5PmIxPQ6
      role: club_rep
    wilmette:
      email: wilmette@nsia.org
      name: Wilmette Rep
      password: $2b$12$79c2unABduOciINw6a95F.SxlpwWy60YS6dlnKimyMX/ponneCsdi
      role: club_rep
